### ISSUE TITLE
App rendersn in a strange way when wisplayed on standard 15 inch Windows laptop

### ISSUE THREAD

**Issue by ghost** [JeffLiusGitHub/pacman#1]
Hi,

Looks like this app doesn't work well for 15 inch laptop screen in FireFox.
The board renders to the full screen and controls are pushed down, so after typing I need to scroll up to see results.
Is it possible to address this issue somehow?
Happy to provide additional information if required.
![image](https://github.com/JeffLiusGitHub/pacman/assets/39324119/0c8692f1-165b-4076-af1a-3dc984e8babb)

Regards,
Alexandr

**Comment by JeffLiusGitHub** [comment]
Sure. I will change the viewport settings. So in the desktop version, you will still see left right arrangement. Thank you for your feedback.

**Comment by JeffLiusGitHub** [comment]
The display layout has been adjusted to accommodate different viewports. On a 15-inch screen, the content is presented in a side-by-side arrangement. For smaller screens, the position of the introduction section has been swapped to enhance user experience and ensure better readability.

**Comment by ghost** [comment]
Hi, thank you, it works well now on desktop, but not on mobile. Which is probably a separate issue. No need to fix as part of this one I think
![Screen Shot 2023-06-07 at 12 49 58](https://github.com/JeffLiusGitHub/pacman/assets/39324119/56322853-055e-446d-80ac-c03aa5dc3be3)

**Comment by JeffLiusGitHub** [comment]
Hi Alexandr,

Thank you for your response. As a programmer, it's important to constantly strive for excellence and provide the best user experience. I will find time later today to fix it.

Best regards
Jeff

**Comment by JeffLiusGitHub** [comment]
Enhanced the user experience by making adjustments to the responsive design, ensuring seamless compatibility with mobile devices, and implementing improvements across various other UI elements.

**Comment by JeffLiusGitHub** [comment]
@SLTKIE Hello Alexandr, I have made some improvements based on your feedback. For more specific details, you can visit the following URL: pacman-4aed0.web.app/. I would also like to thank you for your insightful suggestions.
